name: mysophobia_io
description: nCov-SARS-2 Tracker.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pull_to_refresh: ^1.6.1
  flutter_spinkit: ^4.1.2+1
  auto_route: 0.6.7
  freezed_annotation: 0.11.0+1
  flutter_bloc: 6.0.1
  equatable: ^1.2.3
  dartz: 0.9.1
  data_connection_checker: 0.3.4
  dio: ^3.0.10
  get_it: ^4.0.4
  injectable: 1.0.4
  shared_preferences: 0.5.8
  cached_network_image: ^2.2.0+1
  bubble: ^1.1.9+1
  clipboard_manager: ^0.0.1
  bubble_tab_indicator: ^0.1.4
  sensors: 0.4.2+2
  geolocator: ^5.3.2+2
  geocoder: 0.2.1   
  permission_handler: ^5.0.1
  google_maps_flutter: ^0.5.29
  shimmer: ^1.1.1
  intl: 0.16.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 7.0.0 
  mockito: 4.1.1  
  build_runner:
  auto_route_generator: ^0.6.8
  freezed: ^0.11.5
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  image_path_android: "assets/icon/myso_dark.png"
  image_path_ios: "assets/icon/myso_dark.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: BJohn
      fonts:
        - asset: assets/fonts/Bjohn.otf

    - family: SJoe
      fonts:
        - asset: assets/fonts/SJoe.otf

    - family: IconsX
      fonts:
        - asset: assets/fonts/IconsX.ttf

    - family: OG
      fonts:
        - asset: assets/fonts/OG.ttf
